[OPCUA_NODE]
# example: ns=1;i=2000
TO_PLC_HEARTBEAT_NODE = ns=1;i=2000
TO_PLC_FILE_WRITE_DETECTED_NODE = ns=1;i=2002
OPCUA_SERVER_STATE = ns=0;i=2259
# example: opc.tcp://192.168.2.199:4840
OPCUA_URL = opc.tcp://10.0.0.129:4840

[OPCUA_CONFIG]
# Limited from 20_000-60_000ms
SESSION_TIMEOUT = 30_000

# If server status check fails it initiates reconnect sequence
# Limited from 2-10s
CHECK_SERVER_STATUS_INTERVAL = 5.0

# Heart beat signal to PLC
# Limited from 1-5s
HEART_BEAT_INTERVAL = 3.0

# Limited from 0.2-2s
DELAY_BETWEEN_WRITES = 0.2

# Prevents looping faster than necessary
# Limited from 0.2 to 2s
MAIN_LOOP_DELAY = 0.2

[MDB_FILE_PATH]
# Path to .MDB files, where servopress data is stored.
Example: C:\Users\user\desktop\servodaata
MDB_DIR_PATH = .

[LOG_CONFIG]
# Enable or disable OPCUA_info_logs
# True or False
ENABLE_OPCUA_INFO_LOGS = True
