[OPCUA_NODE]
TO_PLC_HEARTBEAT_NODE = ns=1;i=2000
TO_PLC_FILE_WRITE_DETECTED_NODE = ns=1;i=2002
OPCUA_SERVER_STATE = ns=0;i=2259
OPCUA_URL = opc.tcp://10.0.0.129:4840

[OPCUA_CONFIG]
# SESSION_TIMEOUT in milliseconds
SESSION_TIMEOUT = 30_000

# HEART_BEAT_INTERVAL in seconds
CHECK_STATUS_INTERVAL = 5.0

# DELAY_BETWEEN_WRITES in seconds
DELAY_BETWEEN_WRITES = 0.2

# HEART_BEAT_INTERVAL in seconds
HEART_BEAT_INTERVAL = 3.0

# MAIN_LOOP_DELAY in seconds
MAIN_LOOP_DELAY = 0.2

[MDB_FILE_PATH]
#PATH TO MDB FOLDER # C:\Users\user\desktop\servodaata
MDB_DIR_PATH = .
