# -----------------------ConfigFile--------------------------------
# config.ini file must stay in same directory as opcua_mon.exe
# If STATIC_MONITORED_FILE is false program will generate its own
# file names in this format based on OS time. "9-15-2026-BS.mdb"

# -----------------------OPCUA SETUP-------------------------------
[OPCUA_NODE]
# Example: ns=1;i=2000
TO_PLC_HEARTBEAT_NODE = ns=1;i=2000
TO_PLC_FILE_WRITE_DETECTED_NODE = ns=1;i=2002
OPCUA_SERVER_STATE = ns=0;i=2259
# Example: opc.tcp://192.168.2.199:4840
OPCUA_URL = opc.tcp://10.0.0.129:4840

[OPCUA_CONFIG]
# Limited from 20_000-60_000ms
SESSION_TIMEOUT = 30_000

# Default 4 but causes not responding on gui so made 2s
# Limited from 1.0-4.0s
SOCKET_TIMEOUT = 2

# If server status check fails it initiates reconnect sequence
# Limited from 2.0-10.0s
CHECK_SERVER_STATUS_INTERVAL = 5.0

# Heart beat signal to PLC
# Limited from 1.0-5.0s
HEART_BEAT_INTERVAL = 3.0

# Limited from 0.2-2.0s
DELAY_BETWEEN_WRITES = 0.2

# Prevents looping faster than necessary
# Limited from 0.2-2.0s
MAIN_LOOP_DELAY = 0.2

# -------------------------FILE SETUP-----------------------------------
[MONITORED_DIR_PATH]
# Path to files, where servopress data is stored.
# Example: C:\Users\user\desktop\servodaata
MONITORED_DIR_PATH = .

[LOG_CONFIG]
# Enable or disable OPCUA_info_logs
# True or False
ENABLE_OPCUA_INFO_LOGS = True

# -----------FOR MONITOR STATIC FILE THAT DOESN'T CHANGE NAME------------
# Still uses MONITORED_DIR_PATH
[STATIC_FILE_NAME]
# Example: test_file.txt
STATIC_MONITORED_FILE = test_file.txt
# True or False
STATIC_FILE_MODE = False
