[project]
name = "opcuaproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=50.0.1",
    "opcua>=0.98.13",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
]

[tool.ruff.lint]
ignore = ["F541", "I001"]
