

            [OPCUA_NODE]
            TO_PLC_HEARTBEAT_NODE = ns=1;i=2000
            TO_PLC_FILE_WRITE_DETECTED_NODE = ns=1;i=2002
            OPCUA_SERVER_STATE = ns=0;i=2259
            OPCUA_URL = opc.tcp://10.0.0.129:4840
            [OPCUA_CONFIG]
            #testing empty
            [MONITORED_DIR_PATH]
            #testing empty
            [STATIC_FILE_NAME]
            